- name: Create Cluster Role for Monitoring Services
  community.kubernetes.k8s:
    state: present
    namespace: monitor
    definition:
      apiVersion: rbac.authorization.k8s.io/v1beta1
      kind: ClusterRole
      metadata:
        name: monitor-cr
      rules:
      - apiGroups: [""]
        resources:
        - nodes
        - namespaces
        - events
        - pods
        - secrets
        - services
        verbs: ["get", "list", "watch"]
      - apiGroups: ["extensions"]
        resources:
        - replicasets
        verbs: ["get", "list", "watch"]
      - apiGroups: ["apps"]
        resources:
        - statefulsets
        - deployments
        - replicasets
        verbs: ["get", "list", "watch"]
      - apiGroups:
        - ""
        resources:
        - nodes/stats
        verbs:
        - get
      - nonResourceURLs:
        - "/metrics"
        verbs:
        - get
      - apiGroups:
          - coordination.k8s.io
        resources:
          - leases
        verbs:
          - '*'

- name: Create Service Account for Monitoring Services
  community.kubernetes.k8s:
    state: present
    namespace: monitor
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: monitor
        namespace: monitor

- name: Bind ClusterRole with monitor Service Account
  community.kubernetes.k8s:
    state: present
    namespace: monitor
    definition:
      apiVersion: rbac.authorization.k8s.io/v1beta1
      kind: ClusterRoleBinding
      metadata:
        name: monitor-crb
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: monitor-cr
      subjects:
      - kind: ServiceAccount
        name: monitor
        namespace: monitor
