- name: Create a Horizontal Pod Autoscaler
  community.kubernetes.k8s:
    state: present
    namespace: production
    definition:
      apiVersion: autoscaling/v2beta2
      kind: HorizontalPodAutoscaler
      metadata:
        name: web-hpa
        namespace: production
      spec:
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: web-dep
        minReplicas: 2
        maxReplicas: 11
        behavior:
          scaleDown:
            stabilizationWindowSeconds: 10
        metrics:
        - type: Pods
          pods:
            metric:
              name: apache_connections_total
            target:
              type: AverageValue
              averageValue: 2
