- name: Create ConfigMap for Metricbeat Daemonset Config
  community.kubernetes.k8s:
    state: present
    namespace: monitor
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: metricbeat-daemonset-config
      data:
        metricbeat.yml: |-
          metricbeat.config.modules:
            # Mounted `metricbeat-daemonset-modules` configmap:
            path: ${path.config}/modules.d/*.yml
            # Reload module configs as they change:
            reload.enabled: false

          output.elasticsearch:
            enabled: true
            hosts: "http://elk-svc-int.analysis.svc.cluster.local:9200"

          setup.kibana:
            host: "http://kib-svc.analysis.svc.cluster.local:5601"

- name: Create Configmap for Meticbeat Daemonset Modules
  community.kubernetes.k8s:
    state: present
    namespace: monitor
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: metricbeat-daemonset-modules
      data:
        system.yml: |-
          - module: system
            period: 10s
            metricsets:
              - cpu
              - load
              - memory
              - network
              - process
              - process_summary
              #- core
              #- diskio
              #- socket
            processes: ['.*']
            process.include_top_n:
              by_cpu: 5      # include top 5 processes by CPU
              by_memory: 5   # include top 5 processes by memory

          - module: system
            period: 1m
            metricsets:
              - filesystem
              - fsstat
            processors:
            - drop_event.when.regexp:
                system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)'

- name: Create Cluster Role for Monitoring Services
  community.kubernetes.k8s:
    state: present
    namespace: monitor
    definition:
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: metricbeat
        labels:
          app: metricbeat
      spec:
        selector:
          matchLabels:
            app: metricbeat
        template:
          metadata:
            labels:
              app: metricbeat
          spec:
            serviceAccountName: monitor
            terminationGracePeriodSeconds: 30
            hostNetwork: true
            dnsPolicy: ClusterFirstWithHostNet
            containers:
            - name: metricbeat
              image: docker.elastic.co/beats/metricbeat:7.11.1
              args: [
                "-c", "/etc/metricbeat.yml",
                "-e",
                "-system.hostfs=/hostfs",
              ]
              securityContext:
                runAsUser: 0
              resources:
                limits:
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 100Mi
              volumeMounts:
              - name: config
                mountPath: /etc/metricbeat.yml
                readOnly: true
                subPath: metricbeat.yml
              - name: modules
                mountPath: /usr/share/metricbeat/modules.d
                readOnly: true
              - name: proc
                mountPath: /hostfs/proc
                readOnly: true
              - name: cgroup
                mountPath: /hostfs/sys/fs/cgroup
                readOnly: true
            volumes:
            - name: proc
              hostPath:
                path: /proc
            - name: cgroup
              hostPath:
                path: /sys/fs/cgroup
            - name: config
              configMap:
                defaultMode: 0640
                name: metricbeat-daemonset-config
            - name: modules
              configMap:
                defaultMode: 0640
                name: metricbeat-daemonset-modules
